# 启动端口
spring:
  jackson:
    date-format: yyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://49.232.21.180:3306/javaboy?useUnicode=true&zeroDateTimeBehavior=round&characterEncoding=UTF-8
    username: root
    password: 146118
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

  redis:
    database: 2
    host: 49.232.21.180
    lettuce:
      pool:
        max-active: 8   #最大连接数据库连接数,设 0 为没有限制
        max-idle: 8     #最大等待连接中的数量,设 0 为没有限制
        max-wait: -1ms  #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
        min-idle: 0     #最小等待连接中的数量,设 0 为没有限制
      shutdown-timeout: 100ms
    password: ''
    port: 6379




server:
  port: 9527

mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  global-config:
    # 关闭MP3.0自带的banner
    banner: true
    db-config:
      #主键类型  0:"数据库ID自增",1:"该类型为未设置主键类型", 2:"用户输入ID",3:"全局唯一ID (数字类型唯一ID)", 4:"全局唯一ID UUID",5:"字符串全局唯一ID (idWorker 的字符串表示)";
      id-type: ASSIGN_ID
      # 默认数据库表下划线命名
      table-underline: true
  configuration:
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 返回类型为Map,显示null对应的字段
    call-setters-on-nulls: true

encrypt:
  privateKey: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDkbr4kplIeVBDx
    qow8UfjFQTw41rFzCIxtXyz+UgKDUDcRseprjkpTmsGwzbZjTBsRYK2lebhfmmyv
    Xw7OpsNPWL+6UCk33v5NDbbM76xKTro+3Lmp0YBQzF7PcL06yAhxW0x8apZQnuVL
    JgAgT5Q60HPdlzGt7DpiZDjLoCmdeIvGht5XOzzzpPg8j0OU2zbGeezTaSA4GWbf
    rkXN2US1fCGK1Gwk3BBzCyrxGtFc6Y28mrfigFWOnuKvXsdj1+3MfFyBnbFlGhe1
    giQV6v9Fsim+npyxz2p2q58XCjCZ0xvlG6TBDbpKeJQWzD5R0zrBV5IMBP38VqCt
    TwOSwMBXAgMBAAECggEANCv20XgLGVIp7If/L2epYaPclT6zmIpDSFeMdylT2Zng
    efIgkCAXabDWvAK/vT4MkJN8FWcPbQZf/E3BnAEKanzijTLxtwj/G6oeLgAvYWlJ
    sEHJRbfLjqientIo5dv50aoAdgoB+rfPtrIfJUIHoMcrL1jwx8BENWSedCNIXeZT
    oxlh2LlVeOdMFU9vEA+qWj+Hpta+8xynpUZ3KsN2BD5vOdm7DSZ48bkIFk2MwAxp
    MCU1wyk44PDsvNtX138e8T5B8Um3CLwocKoJlEZ6QP0j8iYfIS1N446T2TBUuYXs
    TglhAkmWRPU/LeqSQyVVNlrimYbuYTlpsMqQDQBvwQKBgQD/0zZo28DPWBOwrADA
    hkztLcUwz8LGOMMceHOgRC4jpdhJj1TJWNcioGglXhDQ398Sg/yseLMxgFcHDvA0
    4kIwHhxhqqCFKZKeEVZY3KiE/5Kj0OC77zklkNYN+tPWmQsgy47V5OWNif3Qrpex
    cpoOIkVxi+BCWAPF3NC5wkdHFQKBgQDklrwOR7QzAhrXJwEYwJZRou+JarTkkdCz
    ucRaiVmRZk+jBrOuuEpU/FWvP8C/iZvnyE+t9I86DDKNiZSqifLyFDiFCoJvXy+c
    /x4SrOBDJHl4QiCk17gUuHf9Eb37JsX3M3MZ6hGW0PmqlmwZKCh5ukwf4LdGPkFt
    lxc+miWEuwKBgDDYQf45XxH3riLAZJBd1BhA8fKE6JpyQgaQlPsXqXuS8b3xyO18
    se7hk6D22d0XsX7WhorjrMsZxwQI/SILxTlstlyLeISUUHMvuj3TO7XRGk1+1znq
    zg13HveiWYoSxIYpd4ctYgrpOvX6L+poiDOEpZ+tZk8kgOvpYkzlZDiVAoGBALwQ
    49Gf3rrkrW58MaPKtyGdOxREzWUMLrffS5PtUtqUYUrQdb528vjuzhQsEInFTpao
    sB1/iuMILANUwRJ6An52cnXKyruUhZjWMEjPIIc9GA7/4NmefV3W0ylLkpFyOgeC
    td0JPcVmUzKtJWyhJIPZ6U2E1WSeTbg7Sa2ApwOHAoGBAOLbpmibOF+PPjIsQ0Dg
    Qe6IriVLwcTAUkMJE+nu7G6F/xOMe3DXWHcEqctFlBojn0l0rzwQ1d+QEhMvw0mr
    bpzmbegeBqJFAZoArNUhQXpJP5p8LK7/nn6Cxo4rxGXxWLzfC2RttPSCx9gCrVQ+
    sDGe5Jk8qKaVUZA3Yvr45rFM
  publicKey: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA5G6+JKZSHlQQ8aqMPFH4
    xUE8ONaxcwiMbV8s/lICg1A3EbHqa45KU5rBsM22Y0wbEWCtpXm4X5psr18OzqbD
    T1i/ulApN97+TQ22zO+sSk66Pty5qdGAUMxez3C9OsgIcVtMfGqWUJ7lSyYAIE+U
    OtBz3Zcxrew6YmQ4y6ApnXiLxobeVzs886T4PI9DlNs2xnns02kgOBlm365FzdlE
    tXwhitRsJNwQcwsq8RrRXOmNvJq34oBVjp7ir17HY9ftzHxcgZ2xZRoXtYIkFer/
    RbIpvp6csc9qdqufFwowmdMb5RukwQ26SniUFsw+UdM6wVeSDAT9/FagrU8DksDA
    VwIDAQAB
  #是否开启加密 true
  open: true
  # 是否打印加解密log
  showLog: true